#!/bin/sh

# This shell script installs the pyFilteredAspell command into the user's
# `.local/bin`, `.config/pyFilteredAspellFilters` and
# `.config/extraCommieParsers` respectively

# Ensure the user's config directory exists
mkdir -p ~/.config

# Copy over the existing filters
cp -r pyFilteredAspellFilters ~/.config

# Copy over the extra Commie based parser
cp -r extraCommieParsers ~/.config

# Ensure the user's bin directory exists
mkdir -p ~/.local/bin

# Copy the pyFilteredAspell command
cp pyFilteredAspell ~/.local/bin

# Done!
